export const infoContent = {
  en: {
    about: { eyebrow: 'OUR PURPOSE', title: ['A shorter distance', 'between people.'], intro: 'HelaG helps small scale farmers and local businesses in Sri Lanka reach more customers without needing a smartphone, website, or digital payment account.', blocks: [['Built around real conversations.', 'Our coordinators collect product details, prices, quantities, and contact numbers through mobile calls and text messages. Sellers can participate with the tools they already use.'], ['Made for direct connection.', 'Buyers discover what is available on the island, then contact the seller directly. Orders, delivery, and payment stay between buyer and seller by phone or SMS.'], ['Rooted in local value.', 'When more people can find local goods, more of the value from each sale stays with the people who grow, make, and sell them.']] },
    faq: { eyebrow: 'NEED TO KNOW', title: ['Questions, kept', 'simple.'], intro: 'Everything you need to know about finding a seller, placing an order, and supporting local livelihoods through HelaG.', items: [['How do I place an order?', 'Open a listing on the map and use the Call seller or Send SMS button. Tell the seller what you need and agree on collection, delivery, and payment details directly.'], ['Does HelaG process payments?', 'No. HelaG does not handle money or online payments. All transactions are arranged directly between buyers and sellers using calls or mobile messages.'], ['How are listings added?', 'Local administrators collect information from farmers and businesses by phone or SMS, verify the details, and publish the location and products on the map.'], ['Can I list my own products?', 'Yes. Contact our coordination team with your business name, products, prices, quantities, phone number, and location details.']] },
    contact: { eyebrow: 'GET IN TOUCH', title: ["Let's keep it", 'local.'], intro: 'Whether you are a buyer, farmer, business owner, or community coordinator, we would like to hear from you.', cards: [['GENERAL ENQUIRIES', 'Say hello.', 'For buyer questions, partnership ideas, and general information.'], ['PHONE & SMS', 'Talk to our team.', 'Monday to Friday, 9:00 am - 5:00 pm Sri Lanka time'], ['FOR SELLERS', 'Bring your goods.', 'Have products to share? Send us your business name, location, product details, price, quantity, and contact number by SMS.', 'Send an SMS ->']] },
    back: 'Back to browse market',
  },
  si: {
    about: { eyebrow: 'අපගේ අරමුණ', title: ['මිනිසුන් අතර', 'කෙටි දුරක්.'], intro: 'HelaG ශ්‍රී ලංකාවේ කුඩා පරිමාණ ගොවීන්ට සහ දේශීය ව්‍යාපාරවලට ස්මාර්ට් දුරකථනයක්, වෙබ් අඩවියක් හෝ ඩිජිටල් ගෙවීම් ගිණුමක් නොමැතිව වැඩි ගනුදෙනුකරුවන් වෙත ළඟා වීමට උපකාරී වේ.', blocks: [['සැබෑ සංවාද මත ගොඩනගා ඇත.', 'අපගේ සම්බන්ධීකාරකවරුන් දුරකථන ඇමතුම් සහ කෙටි පණිවිඩ මගින් නිෂ්පාදන විස්තර, මිල, ප්‍රමාණ සහ සම්බන්ධතා අංක එකතු කරයි.'], ['සෘජු සම්බන්ධතාව සඳහා.', 'ගැනුම්කරුවන් දිවයින පුරා ඇති දේ සොයාගෙන විකුණුම්කරු සමඟ සෘජුව සම්බන්ධ වේ. ඇණවුම්, බෙදාහැරීම් සහ ගෙවීම් දෙපාර්ශ්වය අතර පවතී.'], ['දේශීය වටිනාකමට මුල් බැස ඇත.', 'වැඩි දෙනෙකුට දේශීය භාණ්ඩ සොයා ගත හැකි විට, සෑම අලෙවියක වටිනාකමක්ම වගා කරන, නිෂ්පාදනය කරන සහ විකුණන පුද්ගලයන් සමඟ රැඳී පවතී.']] },
    faq: { eyebrow: 'දැනගත යුතු දේ', title: ['ප්‍රශ්න, සරලව', 'පිළිතුරු.'], intro: 'විකුණුම්කරුවෙකු සොයා ගැනීම, ඇණවුමක් කිරීම සහ දේශීය ජීවනෝපායන්ට සහාය වීම පිළිබඳ ඔබ දැනගත යුතු සියල්ල.', items: [['මම ඇණවුමක් කරන්නේ කෙසේද?', 'සිතියමේ ලැයිස්තුවක් විවෘත කර විකුණුම්කරු අමතන්න හෝ SMS යවන්න බොත්තම භාවිතා කරන්න. ඔබට අවශ්‍ය දේ සඳහන් කර එකතු කිරීම, බෙදාහැරීම සහ ගෙවීමේ විස්තර සෘජුව එකඟ කර ගන්න.'], ['HelaG ගෙවීම් සකසනවාද?', 'නැත. HelaG මුදල් හෝ මාර්ගගත ගෙවීම් හසුරුවන්නේ නැත. සියලු ගනුදෙනු ඇමතුම් හෝ ජංගම පණිවිඩ මගින් ගැනුම්කරුවන් සහ විකුණුම්කරුවන් අතර සෘජුව සංවිධානය වේ.'], ['ලැයිස්තු එකතු කරන්නේ කෙසේද?', 'දේශීය පරිපාලකවරුන් දුරකථන හෝ SMS මගින් තොරතුරු එකතු කර, ඒවා තහවුරු කර, ස්ථානය සහ නිෂ්පාදන සිතියමට ප්‍රකාශ කරයි.'], ['මගේම නිෂ්පාදන ලැයිස්තුගත කළ හැකිද?', 'ඔව්. ඔබේ ව්‍යාපාර නාමය, නිෂ්පාදන, මිල, ප්‍රමාණ, දුරකථන අංකය සහ ස්ථාන විස්තර සමඟ අපගේ සම්බන්ධීකරණ කණ්ඩායම අමතන්න.']] },
    contact: { eyebrow: 'සම්බන්ධ වන්න', title: ['අපි එය', 'දේශීයව තබමු.'], intro: 'ඔබ ගැනුම්කරුවෙකු, ගොවියෙකු, ව්‍යාපාර හිමියෙකු හෝ ප්‍රජා සම්බන්ධීකාරකයෙකු නම්, ඔබෙන් අසන්න අපි කැමතියි.', cards: [['සාමාන්‍ය විමසීම්', 'ආයුබෝවන් කියන්න.', 'ගැනුම්කරු ප්‍රශ්න, හවුල්කාරී අදහස් සහ සාමාන්‍ය තොරතුරු සඳහා.'], ['දුරකථන සහ SMS', 'අපගේ කණ්ඩායම සමඟ කතා කරන්න.', 'සඳුදා සිට සිකුරාදා දක්වා, පෙ.ව. 9.00 සිට ප.ව. 5.00 දක්වා ශ්‍රී ලංකා වේලාවෙන්'], ['විකුණුම්කරුවන් සඳහා', 'ඔබේ භාණ්ඩ රැගෙන එන්න.', 'බෙදාගැනීමට නිෂ්පාදන තිබේද? ඔබේ ව්‍යාපාර නාමය, ස්ථානය, නිෂ්පාදන විස්තර, මිල, ප්‍රමාණය සහ සම්බන්ධතා අංකය SMS මගින් අපට එවන්න.', 'SMS එකක් යවන්න ->']] },
    back: 'වෙළඳපොළ වෙත ආපසු',
  },
  ta: {
    about: { eyebrow: 'எங்கள் நோக்கம்', title: ['மக்களுக்கு இடையில்', 'குறுகிய தூரம்.'], intro: 'சிறு விவசாயிகள் மற்றும் உள்ளூர் வணிகங்கள் ஸ்மார்ட்போன், இணையதளம் அல்லது டிஜிட்டல் பணப்பரிவர்த்தனைக் கணக்கு இல்லாமலே அதிக வாடிக்கையாளர்களை அடைய HelaG உதவுகிறது.', blocks: [['உண்மையான உரையாடல்களை மையமாகக் கொண்டது.', 'எங்கள் ஒருங்கிணைப்பாளர்கள் அழைப்புகள் மற்றும் குறுஞ்செய்திகள் மூலம் பொருள் விவரங்கள், விலைகள், அளவுகள் மற்றும் தொடர்பு எண்களைச் சேகரிக்கிறார்கள்.'], ['நேரடி தொடர்பிற்காக உருவாக்கப்பட்டது.', 'வாங்குபவர்கள் தீவு முழுவதும் கிடைப்பவற்றைக் கண்டறிந்து விற்பனையாளரை நேரடியாகத் தொடர்புகொள்கிறார்கள். ஆர்டர், விநியோகம் மற்றும் பணம் தொடர்பான ஏற்பாடுகள் இரு தரப்பினரிடமும் இருக்கும்.'], ['உள்ளூர் மதிப்பில் வேரூன்றியது.', 'அதிக மக்கள் உள்ளூர் பொருட்களைக் கண்டறியும்போது, ஒவ்வொரு விற்பனையின் மதிப்பும் அதை வளர்க்கும், உருவாக்கும் மற்றும் விற்கும் மக்களிடம் நிலைத்திருக்கும்.']] },
    faq: { eyebrow: 'தெரிந்துகொள்ள வேண்டியது', title: ['கேள்விகள், எளிய', 'பதில்கள்.'], intro: 'விற்பனையாளரைக் கண்டறிதல், ஆர்டர் இடுதல் மற்றும் உள்ளூர் வாழ்வாதாரங்களை ஆதரித்தல் பற்றிய அனைத்தும்.', items: [['நான் எப்படி ஆர்டர் இடுவது?', 'வரைபடத்தில் ஒரு பட்டியலைத் திறந்து விற்பனையாளரை அழைக்கவும் அல்லது SMS அனுப்பவும் என்பதைப் பயன்படுத்துங்கள். உங்களுக்கு வேண்டியதைச் சொல்லி சேகரிப்பு, விநியோகம் மற்றும் கட்டண விவரங்களை நேரடியாக ஒப்புக்கொள்ளுங்கள்.'], ['HelaG பணப்பரிவர்த்தனைகளைச் செயலாக்குமா?', 'இல்லை. HelaG பணம் அல்லது இணையவழி கட்டணங்களைக் கையாளாது. அனைத்து பரிவர்த்தனைகளும் வாங்குபவர்களுக்கும் விற்பனையாளர்களுக்கும் இடையே நேரடியாக ஏற்பாடு செய்யப்படுகின்றன.'], ['பட்டியல்கள் எவ்வாறு சேர்க்கப்படுகின்றன?', 'உள்ளூர் நிர்வாகிகள் தொலைபேசி அல்லது SMS மூலம் தகவல்களைச் சேகரித்து, சரிபார்த்து, இடம் மற்றும் பொருட்களை வரைபடத்தில் வெளியிடுகிறார்கள்.'], ['எனது சொந்தப் பொருட்களைப் பட்டியலிடலாமா?', 'ஆம். உங்கள் வணிகப் பெயர், பொருட்கள், விலைகள், அளவுகள், தொலைபேசி எண் மற்றும் இட விவரங்களுடன் எங்கள் ஒருங்கிணைப்புக் குழுவைத் தொடர்புகொள்ளுங்கள்.']] },
    contact: { eyebrow: 'தொடர்பில் இருங்கள்', title: ['இதனை', 'உள்ளூராக வைத்திருப்போம்.'], intro: 'நீங்கள் வாங்குபவர், விவசாயி, வணிக உரிமையாளர் அல்லது சமூக ஒருங்கிணைப்பாளர் என்றால், உங்களிடமிருந்து கேட்க விரும்புகிறோம்.', cards: [['பொது விசாரணைகள்', 'வணக்கம் சொல்லுங்கள்.', 'வாங்குபவர் கேள்விகள், கூட்டாண்மை யோசனைகள் மற்றும் பொதுத் தகவல்களுக்கு.'], ['தொலைபேசி மற்றும் SMS', 'எங்கள் குழுவுடன் பேசுங்கள்.', 'திங்கள் முதல் வெள்ளி வரை, காலை 9.00 முதல் மாலை 5.00 வரை இலங்கை நேரம்'], ['விற்பனையாளர்களுக்கு', 'உங்கள் பொருட்களைக் கொண்டு வாருங்கள்.', 'பகிர்வதற்கு பொருட்கள் உள்ளதா? உங்கள் வணிகப் பெயர், இடம், பொருள் விவரங்கள், விலை, அளவு மற்றும் தொடர்பு எண்ணை SMS மூலம் எங்களுக்கு அனுப்புங்கள்.', 'SMS அனுப்பவும் ->']] },
    back: 'சந்தைக்குத் திரும்பு',
  },
}